[server]
address = "127.0.0.1"
maxUploadSize = 150
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FBBF24"
backgroundColor = "#141010"
secondaryBackgroundColor = "#241D18"
textColor = "#F5F0EB"
